# fly.toml app configuration file generated for git-solitary-river-4859 on 2024-11-16T00:21:49+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'git-solitary-river-4859'
primary_region = 'sin'

[build]

[env]
 SQLALCHEMY_DATABASE_URI = "postgresql://postgres:fQiRcHy2IIo4JOD@informationdesign-db.flycast:5432"

[http_service]
 internal_port = 8080
 force_https = true
 auto_stop_machines = 'stop'
 auto_start_machines = true
 min_machines_running = 0
 processes = ['app']

[[vm]]
 memory = '256mb'
 cpu_kind = 'shared'
 cpus = 1